### ISSUE TITLE
[FEATURE] Display an error message on preset load, when a driver couldn't be found

### ISSUE THREAD

**Issue by TimSusa** [TimSusa/midi-sliders#71]
display an error message on preset load, when a driver couldn't be found,

**Comment by alectroniq** [comment]
a missing driver is not marked in red (anymore), but the tooltip displays it correctly. 
- can we highlight missing drivers in red?
- Also please add a message in Main View though, because it shouldn't be necessary to check the Global Settings. This message should lead directly to the Global View (by click or automated) and show the highlighted missing drivers.

**Comment by TimSusa** [comment]
First issue is fixed with: https://github.com/TimSusa/midi-sliders/commit/0ebca6f6708989d2d30fa0c79ce8387c23a80083

**Comment by TimSusa** [comment]
Can we compromise a mvp: It leads you to the global settings, only if some corrupted driver was found. Otherwise, it lets you in the main view if everything is ok?

**Comment by alectroniq** [comment]
yes sure, that's how it should be :) 

test: red highlights are working!
